Add bundler update to work around build issues
The current version of bundler used on travis causes the following error
NoMethodError: undefined methodspec' for nil:NilClass`

This is a fairly well understood issue, discussed here:
* https://github.com/travis-ci/travis-ci/issues/5239
* https://github.com/bundler/bundler/issues/3558